######################################################################
# @author      : t-hara (t-hara@$HOSTNAME)
# @file        : Makefile
# @created     : Tuesday Oct 25, 2022 20:34:11 JST
######################################################################

main:
	$(CC) -Wall -fPIC -c dt.c
	$(CC) -shared dt.o -o dt.so
	# ./learn.py --dataroot flows.pickle --function train_dt 

